server:
  port: 8080 # 服务端口

spring:
  application:
    name: admin-backend # 服务名称
  thymeleaf:
    cache: false # 开发环境关闭缓存
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # 注册中心地址
  instance:
    prefer-ip-address: true # 注册时使用IP地址
    